### ISSUE TITLE
Test staging environment with real data

### ISSUE THREAD

**Issue by bfirsh** [embassynetwork/modernomad#323]
There is now a staging environment at ~~https://embassynetwork-staging.herokuapp.com/~~ https://staging.embassynetwork.com/ as the result of #303.

Before we consider whether we want to deploy the production environment to Heroku, we should actually check the damn thing works.

## Tasks

- [x] Set up Stripe test account @jessykate 
- [x] Put production database dump on staging @jessykate 
- [x] Set up Mailgun test account @jessykate 
- [x] Set up Sentry so we can keep track of any exceptions that happen when testing https://github.com/embassynetwork/modernomad/issues/309 @jessykate 
- [x] Put static files dump on S3 @bfirsh 
  - ``` s3cmd sync --region us-east-1 -rv webapp/media/* s3://staging-media.embassynetwork.com/public/ ```
- [x] Set up scheduled tasks (see #326)
  - set up to run at 11:00 UTC / 03:00 PST, which seems a reasonable timezone compromise
- [x] Set up static files so they’ll be served by Cloudflare CDN (should work out of box with whitenoise, but double check)
- [x] Document how static files are done (@bfirsh ) https://github.com/embassynetwork/modernomad/pull/426
- [x] Put behind CDN and real domain
- [x] Check all the happy booking paths work with Stripe test account (@jessykate, see #339 )
- [x] Check file upload stuff on S3 all works as expected
- [x] Put behind basic auth so people don't use it by mistake (@bfirsh, see #380 )

**Comment by bfirsh** [comment]
I have put staging behind Cloudflare at https://staging.embassynetwork.com/. Media is also served via Cloudflare at https://staging-media.embassynetwork.com/.

**Comment by bfirsh** [comment]
Just gonna say we've done this and move #351 to #324 as a blocker. Woooooooo :tada:

**Comment by jonathan-s** [comment]
🎉 🎉
