### ISSUE TITLE
Headless browser tests for key workflows

### ISSUE THREAD

**Issue by jessykate** [embassynetwork/modernomad#339]
Use a tool like https://www.cypress.io/ to create headless browser tests for key workflows like payments, mail, bookings. 

Relates to #307 and indirectly #302. 

## Key workflows to test

registration (profile creation) via:
- [x] new user making a booking request (#370)

room search, selection and booking request submission workflow for:
- [x] new users (just being explicit; this is the same as "new user making a booking request" above) (#370)  
- [x] logged in users (claimed by @bfirsh, in #450 )
- [x] logged out users with accounts (claimed by @bfirsh, in #450 )
 
Payments and booking management
- [x] user adding credit card to their profile (claimed by @bfirsh, in #450  )
- [x] location admin confirms booking and charges card (claimed by @bfirsh, in #450 )
- [x] location admin confirms booking and charges card but payment fails (claimed by @bfirsh, in #450 )
- [ ] location admin can send an email manually
- [x] Refund (claimed by @bfirsh, in #450)

Emails
- [ ] daily resident, guest and admin email functions work when 

## Other workflows

- [ ] new user registering and RSVP-ing for an event

**Comment by jonathan-s** [comment]
@jessykate @bfirsh What flows should be tested here, can we make a list?

**Comment by jonathan-s** [comment]
Opening again in case more tests should is necessary for go-live.

**Comment by jessykate** [comment]
added a list above. Feel free to edit/contribute, this is my first pass at critical workflows/functionalities.

**Comment by bfirsh** [comment]
I have made another list of less important workflows, just for the sake of prioritisation. Moved registration through RSVP-ing for event to there, because it's probably less important than booking a room?

**Comment by bfirsh** [comment]
done! superceded by #460
